local PabloLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/BatuKvi123/PabloLibV3/main/PabloLibV3"))()local window = PabloLib:Create(
"OxyHubV3", -- Name here.
"Enabled", -- If you want draggable set here to "Enabled" if you dont want set to "Disabled".
"p" -- You can put any keybind here to open close.
)local tab1 = window:CreateTab("Abilities (not Spamable)")tab1:CreateButton("Ravage", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Normal.Ravage:FireServer(ohNumber1)
print("Hello World")
end)tab1:CreateButton("Swift Sweep", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Normal.SweepSwift:FireServer(ohNumber1)
print("Hello World")
end)tab1:CreateButton("Corrateral Ruin", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Normal.CollateralRuin:FireServer(ohNumber1)
print("Hello World")
end)local tab1 = window:CreateTab("Ult Moves")tab1:CreateButton("Stoic Bomb", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Ultimate.StoicBomb:FireServer(ohNumber1)
print("Hello World")
end)tab1:CreateButton("20-20-20 dropkick", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Ultimate.DropKick:FireServer(ohNumber1)
print("Hello World")
end)tab1:CreateButton("Five Seasons", function()-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 1

game:GetService("ReplicatedStorage").Remotes.KJ.Ultimate.FiveSeasons:FireServer(ohNumber1)
print("Hello World")
end)